[project]
name = "py"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pandas>=2.3.3",
    "pandas-geojson>=2.2.1",
    "requests>=2.32.5",
    "tabulate>=0.9.0",
]
